### ISSUE TITLE
Default Singularity module on Cirrus does not have `-v` option for `cache list`

### ISSUE THREAD

**Issue by cc-a** [ImperialCollegeLondon/2020-07-13-Containers-Online#7]
> [ccaveayl@cirrus-login1 ~]$ singularity cache list -v
> Usage:
>   singularity [global options...] cache list [list options...]
> 
> Run 'singularity cache list --help' for more detailed usage information.

**Comment by jcohen02** [comment]
It looks like this is a result of using singularity v3.2.1 which is the default version. With 3.5.3, this is not an issue. The issue of singularity versions is also raised in #8 and the plan should be to move the default to 3.5.3, or, we can add some info to the course material highlighting how to load the correct module.

**Comment by aturner-epcc** [comment]
Changed Cirrus default to v3.5.3 so closing.
