### ISSUE TITLE
`singularity inspect` fails on Cirrus with default Singularity module

### ISSUE THREAD

**Issue by cc-a** [ImperialCollegeLondon/2020-07-13-Containers-Online#8]
> [ccaveayl@cirrus-login1 ~]$ singularity inspect -r hello-world.sif 
> FATAL:   fork/exec /lustre/sw/singularity/3.2.1/libexec/singularity/bin/starter-suid: no such file or directory: 
>

**Comment by aturner-epcc** [comment]
@cc-a Try using the more recent version of Singularity on Cirrus (3.5.3) `module load singularity/3.5.3`. I need to check with the team, but will hopefully switch default to the new version before the course.

**Comment by cc-a** [comment]
Works fine with the newer version just wanted to highlight but unlikely to be an issue if default version is swapped.

**Comment by jcohen02** [comment]
Thanks for pointing this out @cc-a. The default version has now been changed so this is no longer a problem and I'm closing the issue.
